name: opulizer
description: "An app made to represent data in the form of charts"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.2
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.11
  change_app_package_name: ^1.2.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: 2.4.0

flutter:
  uses-material-design: true
